version: 0.2

phases:
  install:
    commands:
      - echo Setting up Maven settings...
      - mkdir -p ~/.m2
      - |
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <mirrors>
            <mirror>
              <id>central</id>
              <name>Maven Central Mirror</name>
              <url>https://repo.maven.apache.org/maven2</url>
              <mirrorOf>central</mirrorOf>
            </mirror>
          </mirrors>
        </settings>
        EOF

  pre_build:
    commands:
      - echo Installing dependencies...
      - yum install -y jq maven
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=185187793433
      - REGION=us-east-1
      - REPO_NAME=spring-demo
      - IMAGE_TAG=v1.$CODEBUILD_BUILD_NUMBER
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo Building the JAR file using Maven...
      - |
        for i in {1..5}; do
          mvn clean install && break || { echo "Maven build failed. Retrying in 15 seconds..."; sleep 15; }
        done
      - echo Checking if JAR was created...
      - ls -l target/
      - test -f target/*.jar || { echo "ERROR: No JAR file found in target/. Failing build."; exit 1; }
      - echo Building Docker image...
      - docker build -t ${REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${REPO_NAME}:${IMAGE_TAG} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:${IMAGE_TAG}

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:${IMAGE_TAG}
      - echo Creating Kubernetes deployment files...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:${IMAGE_TAG}|g" k8s/deployment.yaml > k8s-out/deployment.yaml
      - cp k8s/service.yaml k8s-out/service.yaml
      - echo Listing final output files...
      - ls -R k8s-out

artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml


