apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
  labels:
    app: spring-demo
spec:
  type: LoadBalancer
  selector:
    app: spring-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
 
